node_js:
- '0.10'
language: node_js

sudo: false

env:
  global:
    # Setting these because they are required for tests to pass.
    - export GH_USERNAME=someuser
    - export GH_PASSWORD=somepass

before_script:
- git branch -v
- git remote show origin
- git remote -v
