---
# Where this application will be hosted. Can be overrideen in production
# environments with $HOST and $PORT.
host: "localhost"
port: 8081

# Location of the directory where logs will be written.
logDirectory: "logs"

# Default log level.
logLevel: "debug"

# contributors: URL to CSV file containing a list of people who've
#               signed Numenta's contributor license. This is used
#               for validating pull requests, ensuring the author
#               has signed our license.
contributors: "http://staging.numenta.org/resources/contributors.csv"

# hooks: Node require paths to scripts, called with webhook payload
#        when the key event occurs.
#   - push: Occurs when code is pushed to `master` branch of the
#           specified repository.
#   - build: Occurs on successfull build of the `master` branch of
#           specified repository.
hooks:
  numenta/nupic:
    build:
     - "./webhooks/event-responses/update-research"
     - "./webhooks/event-responses/update-regression"

# These are the GitHub events the server will subscribe to when setting up
# webhooks. Any exiting webhooks for the current server URL will be deleted.
githooks:
  - issue_comment
  - pull_request
  - push
  - status

notifications:
  pr_review: discourse-committers@numenta.org

repos:

  # Primary NuPIC repositories
  - slug: numenta/nupic
    type: primary
    coverage: true

  - slug: numenta/nupic.core
    type: primary
    coverage: true

  # Tooling repositories
  - slug: numenta/nupic.tools
    type: tooling
    travis: true
    coverage: true

  - slug: numenta/nupic.regression
    type: tooling

  - slug: rhyolight/sprinter.js
    type: tooling
    travis: true
    coverage: true
    deploy: "https://www.npmjs.org/package/sprinter"
    monitor: false

  - slug: rhyolight/sprinter-dash
    type: tooling
    deploy: "https://www.npmjs.org/package/sprinter-dash"
    monitor: false

  - slug: "rhyolight/travis-foreman"
    type: tooling
    travis: true
    coverage: true
    deploy: "https://pypi.python.org/pypi/pycept/"
    monitor: false

  # Support projects
  - slug: numenta/NAB
    type: support

  - slug: numenta/htmresearch
    type: support

  - slug: numenta/htmresearch-core
    type: support

  - slug: numenta/cortipy
    type: support
    travis: true
    coverage: true

  # NuPIC applications
  - slug: numenta/numenta-apps
    type: app
    monitor: false

  - slug: numenta/nupic.geospatial
    type: app
    travis: true
    coverage: true

  - slug: nupic-community/nupic.studio
    type: app
    monitor: false

  - slug: numenta/nupic.cerebro
    type: app

  - slug: numenta/nupic.cerebro2
    type: app

  - slug: numenta/nupic.cerebro2.server
    type: app

  - slug: numenta/nupic.nlp-examples
    type: app

  - slug: numenta/htm.java-examples
    type: app
    travis: true
    coverage: true

  # Ports of HTM to other environments
  - slug: numenta/htm.java
    type: port
    travis: true
    coverage: true
